/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Gap212.Definitions
public import Gap212.Equidistribution.Basic
public import Gap212.Sieve.Certificate
public import Gap212.Endgame.DHL
public meta import Gap212.Attr

/-!
# The top-level architecture: `DHL[45,2]` and `H₁ ≤ 212`

The proof has the shape

    arithmetic certificate + variational certificate ⟹ DHL[45,2] ⟹ H₁ ≤ 212.

This module states it in the two-variable shape, where coefficient sequences take the scale `x`
as an argument. The second implication is proved here, via `Gap212.Endgame.DHL`; the first is
the sieve criterion, which in this module is a hypothesis. The main theorems are proved through the
single-scale forms of `Gap212.Harman.Challenge`, where the sieve criterion and the arithmetic
certificate are both derived (see `Gap212.challengeResidual`).

## The generated modulus family

The sieve criterion consumes two inputs: an arithmetic theorem licensing the moduli generated by
the support, and a strict variational inequality on that support. Making the first precise
requires the family of moduli a support can generate, which is `Qgen` / `Qstar` in
`Gap212.Definitions` ([2, Definition 2]).

A modulus in `Qgen` factors as `e e' ∏ fᵢ ∏ f'ᵢ` where `e e'` is the `x^δ`-smooth part and the `fᵢ`
are the rough factors, each at least `x^δ`, with the rough products capped by the `B` row of the
support and the mixed products capped by its `A` node. The constraints are written multiplicatively
(`N ≤ x ^ c` rather than `logb x N ≤ c`), which is equivalent for `x > 1` and avoids carrying a
logarithm through every statement.

The bound `m, m' ≤ ⌊1/δ⌋` is the one of [2, Definition 2]. A larger `Qstar` would make
`ArithmeticCertificateFamily` a *stronger* hypothesis and hence the final theorem weaker.

## The hypotheses of the assembly

* `Gap212.SieveCriterionFamily` — the sieve criterion of [2, Proposition 1]: the Maynard–Tao
  sieve over the stratified support, with the retreat, mollification and finite-tensor
  construction, the asymptotic evaluation, and the comparison of the main term against the
  error. It is not reused from `PrimeGapsLib`, whose sieve requires `θ < 1/2` and is restricted
  to the `ε`-enlarged simplex.
* `Gap212.ArithmeticCertificateFamily` — equidistribution of the prime indicator over the moduli the
  support `gap212Params` generates, which the five Type estimates, bilinear Bombieri–Vinogradov, the
  half-level transition and the Harman decomposition together deliver.
* `Gap212.Gap212Certificate` — the variational inequality.

## Main results

* `Gap212.nthPrimeGapLE_212_of_dhl` — `DHL[45,2] ⟹ H₁ ≤ 212`, using the explicit diameter-212
  admissible 45-tuple.
* `Gap212.nthPrimeGapLE_212_of_inputsFamily` / `primeGapLE_212_of_inputsFamily` — the assembly
  from the three hypotheses above.

## Main definitions

* `Gap212.DHL k m`: every admissible `k`-tuple has infinitely many translates with `≥ m` primes.
* `Gap212.Qgen`, `Gap212.Qstar`: the modulus family generated by a support, declared in
  `Gap212.Definitions`.
* `Gap212.HasEquidistributionOverQstarFamily`: the equidistribution norm over that family.
* `Gap212.primeIndicatorFamily`: `1_ℙ` in the two-variable shape.
-/

@[expose] public section

namespace Gap212

attribute [gap212 "def_qgen"] Qgen
attribute [gap212 "def_qstar"] Qstar

open Finset MeasureTheory

/-! ## `DHL[k,m]` -/

/-- **`DHL[k,m]`**: every admissible `k`-tuple has infinitely many translates containing at least
`m` primes. The tuple is presented as a strictly monotone `h : Fin k → ℕ`, so that
`Finset.image h Finset.univ` is the `k`-element set and its diameter is `h (k-1) - h 0`. -/
@[gap212 "def_dhl"]
def DHL (k m : ℕ) : Prop :=
  ∀ h : Fin k → ℕ, StrictMono h → (Finset.image h Finset.univ).Admissible →
    {n : ℕ | m ≤ #{i : Fin k | (n + h i).Prime}}.Infinite

/-- **`DHL[45,2]` implies `H₁ ≤ 212`.** `DHL[45,2]` gives `p_{n+1} - p_n ≤ 212` for arbitrarily
large `n`, by applying it to the explicit admissible 45-tuple `H45` of diameter 212. -/
theorem nthPrimeGapLE_212_of_dhl (h : DHL 45 2) : NthPrimeGapLE 212 :=
  nthPrimeGapLE_212_of_dhl45
    (h h45 h45_strictMono (by rw [image_h45]; exact admissible_H45))

/-- The pair form: beyond every bound there are two primes `p < q` with `q ≤ p + 212`. -/
theorem primeGapLE_212_of_dhl (h : DHL 45 2) : PrimeGapLE 212 :=
  primeGapLE_of_nthPrimeGapLE (nthPrimeGapLE_212_of_dhl h)

/-! ## The moduli a support generates -/

open Classical in
/-- **The equidistribution norm over a support's moduli**, [2, Definition 3]. The squarefree moduli
of `Qstar` are summed against the discrepancy of `f` in a primitive class, and the total must beat
`x / log(x)^A` for every `A`.

The quantifier order records what the implied constant may depend on: `c` is chosen after `ε₀` and
`A` and before `x` and `a`, which is the `≪_{A,ε₀}` of [2, Definition 3]. -/
def HasEquidistributionOverQstarFamily (p : SupportParams) (f : ℕ → ℝ → ℂ) : Prop :=
  ∀ ε₀ > (0 : ℝ), ∀ A > (0 : ℝ), ∃ c > (0 : ℝ), ∀ x : ℝ, 1 < x → ∀ a : ℕ, CoprimeBelow a x →
    ∑ q ∈ {q ∈ Finset.Icc 1 ⌊x⌋₊ | q ∈ Qstar p x ε₀ ∧ Squarefree q},
      ‖(∑ n ∈ dyadic x with n ≡ a [MOD q], f n x) -
        (1 / (Nat.totient q : ℂ)) * ∑ n ∈ dyadic x with Nat.Coprime n q, f n x‖ ≤
      c * x / (Real.log x) ^ A

/-- The prime indicator `1_ℙ` in the two-variable shape, used by the `...Family` declarations of
this module and of `Gap212.Harman`, `Gap212.Sieve.Criterion` and `Gap212.Sieve.GPY`.

The single-scale prime indicator is `Gap212.primeIndicator : ℕ → ℂ`, and the Harman reduction
concludes about `Gap212.primeInterval x`; `Gap212.Harman.Challenge` states `ArithmeticCertificate`
and `SieveCriterion` at `primeInterval x`. -/
def primeIndicatorFamily : ℕ → ℝ → ℂ := fun n _ ↦ if n.Prime then 1 else 0

/-! ## The two carried inputs -/

/-- **The sieve criterion** ([2, Proposition 1], in the direct-prime form): equidistribution of the
prime indicator over the moduli a support generates, together with the strict variational inequality
on that support, gives `DHL[k,2]`.

Stated at `c₁ = c₂ = 0`, which is what `ξ₂ = 2/5` forces, so `K` drops out of the
inequality entirely and `Certificate p m 0 0` reads `I(F) < (m+1) J(F)`.

It is not available from `PrimeGapsLib`: that library's `Gaps246.prop_witness` requires
`θ < 1/2` and its support is the `ε`-enlarged simplex, while this method passes the half-level on
a stratified support. -/
def SieveCriterionFamily : Prop :=
  ∀ (p : SupportParams) (m : ℕ),
    HasEquidistributionOverQstarFamily p primeIndicatorFamily → Certificate p m 0 0 → DHL (m + 1) 2

/-- **The arithmetic certificate at the datum**: the prime indicator equidistributes over every
modulus the support `gap212Params` generates.

This is what the five Type estimates deliver, once the support's rough factors have been routed to
them. The routing is the factor-packing argument: conditions (A), (B), (C) and (E) are discharged in
`Gap212.Packing.Basic`, and condition (D) follows from `Gap212.PackingCertificate`
(`Gap212.conditionD_at_datum_all`). Two further analytic inputs are needed and are not implied by
the five estimates — bilinear Bombieri–Vinogradov for the sub-half range, and the Harman/Buchstab
decomposition expressing `1_ℙ` in the decomposition class. -/
def ArithmeticCertificateFamily : Prop :=
  HasEquidistributionOverQstarFamily gap212Params primeIndicatorFamily

/-! ## The assembly -/

/-- **`DHL[45,2]`**, from the sieve criterion, the arithmetic certificate, and the numerical
certificate. `Gap212Certificate` is `Certificate gap212Params 44 0 0`, and `44 + 1 = 45`. -/
theorem dhl45_of_inputsFamily (hsieve : SieveCriterionFamily) (harith : ArithmeticCertificateFamily)
    (hcert : Gap212Certificate) : DHL 45 2 :=
  hsieve gap212Params 44 harith hcert

/-- **`H₁ ≤ 212`**, in the `nth`-prime form: from the three inputs, `p_{n+1} - p_n ≤ 212` for
arbitrarily large `n`. -/
theorem nthPrimeGapLE_212_of_inputsFamily (hsieve : SieveCriterionFamily)
    (harith : ArithmeticCertificateFamily)
    (hcert : Gap212Certificate) : NthPrimeGapLE 212 :=
  nthPrimeGapLE_212_of_dhl (dhl45_of_inputsFamily hsieve harith hcert)

/-- **`H₁ ≤ 212`**, in the pair form. -/
theorem primeGapLE_212_of_inputsFamily (hsieve : SieveCriterionFamily)
    (harith : ArithmeticCertificateFamily)
    (hcert : Gap212Certificate) : PrimeGapLE 212 :=
  primeGapLE_of_nthPrimeGapLE (nthPrimeGapLE_212_of_inputsFamily hsieve harith hcert)

end Gap212
