/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Gap212.Packing.Basic
public import Mathlib.Data.Fin.Tuple.Basic

/-!
# Building `Ξ`-membership from the two sides of a modulus

A modulus generated by the support factors as `q = e e' ∏_{i<m} fᵢ ∏_{i<m'} f'ᵢ`, with the two
rough groups capped separately by `B_{j,m}` and `B_{j',m'}`. The packing conditions of Proposition
3, by contrast, quantify over a *single pooled* tuple `(y₁, …, y_{m+m'}) ∈ Ξ`, and the partition
they supply is allowed to mix factors from the two sides — which is the whole point, since a
divisor of `q` may be assembled from both.

So the two presentations have to be reconciled once, and this module does it. `Fin.append` pools
the two tuples; the content is that the filters cutting `Ξ`'s two groups pick out exactly the two
halves of the append, so the group sums are the two original sums.

Isolating this here keeps the three factor-extraction lemmas free of reindexing: each builds its
pooled tuple with `mem_Xi_append` and then works only with the partition it gets back.

The lemmas are stated at the weakest algebra each needs — the reindexing facts hold in any additive
commutative monoid, and the entrywise one in any type at all. Only `mem_Xi_append` mentions `Ξ`,
and so only it needs the ordered field.

## Main results

* `Gap212.Packing.sum_filter_append_left` / `sum_filter_append_right`: the two group sums of an
  appended tuple are the sums of its halves.
* `Gap212.Packing.append_mem_of_mem`: every entry of an appended tuple is an entry of one half.
* `Gap212.Packing.append_comp`: applying a function entrywise commutes with appending.
* `Gap212.Packing.mem_Xi_append`: `Ξ`-membership from data on the two sides separately.
-/

@[expose] public section

namespace Gap212.Packing

open Finset

/-! ## Reindexing the two groups

These hold in any additive commutative monoid. -/

section Sums

variable {M : Type*} [AddCommMonoid M] {m₁ m₂ : ℕ}

/-- The first group of an appended tuple — the indices below `m₁` — sums to the sum of the first
half. -/
theorem sum_filter_append_left (u : Fin m₁ → M) (v : Fin m₂ → M) :
    ∑ i ∈ univ.filter (fun i : Fin (m₁ + m₂) ↦ (i : ℕ) < m₁), Fin.append u v i = ∑ i, u i := by
  classical
  rw [Finset.sum_filter, Fin.sum_univ_add]
  simp

/-- The second group of an appended tuple — the indices at or above `m₁` — sums to the sum of the
second half. -/
theorem sum_filter_append_right (u : Fin m₁ → M) (v : Fin m₂ → M) :
    ∑ i ∈ univ.filter (fun i : Fin (m₁ + m₂) ↦ ¬ ((i : ℕ) < m₁)), Fin.append u v i = ∑ i, v i := by
  classical
  rw [Finset.sum_filter, Fin.sum_univ_add]
  simp

/-- Splitting the mass a partition block draws from the two sides. This is what lets a block of the
pooled index set be read back onto the two halves of the modulus. -/
theorem sum_append_eq {I : Finset (Fin (m₁ + m₂))} (u : Fin m₁ → M) (v : Fin m₂ → M) :
    ∑ i ∈ I, Fin.append u v i =
      (∑ i ∈ I.filter (fun i : Fin (m₁ + m₂) ↦ (i : ℕ) < m₁), Fin.append u v i) +
        ∑ i ∈ I.filter (fun i : Fin (m₁ + m₂) ↦ ¬ ((i : ℕ) < m₁)), Fin.append u v i := by
  classical
  exact (sum_filter_add_sum_filter_not I _ _).symm

end Sums

/-! ## Entries

No algebra at all. -/

section Entries

variable {α : Type*} {m₁ m₂ : ℕ}

/-- Every entry of an appended tuple is an entry of one of the halves. -/
theorem append_mem_of_mem {S : Set α} (u : Fin m₁ → α) (v : Fin m₂ → α)
    (hu : ∀ i, u i ∈ S) (hv : ∀ i, v i ∈ S) (i : Fin (m₁ + m₂)) : Fin.append u v i ∈ S := by
  induction i using Fin.addCases with
  | left i => rw [Fin.append_left]; exact hu i
  | right i => rw [Fin.append_right]; exact hv i

/-- Applying a function entrywise commutes with appending. This is what relates the tuple of rough
factors to the tuple of their scaled logarithms: the pooled tuple of logarithms is the pooled tuple
of factors composed with `log_x`. -/
theorem append_comp {α β : Type*} (g : α → β) (u : Fin m₁ → α) (v : Fin m₂ → α)
    (i : Fin (m₁ + m₂)) : g (Fin.append u v i) = Fin.append (g ∘ u) (g ∘ v) i := by
  induction i using Fin.addCases with
  | left i => simp
  | right i => simp

end Entries

/-! ## `Ξ`-membership -/

section Xi

variable {𝕜 : Type*} [Field 𝕜] [LinearOrder 𝕜] [IsStrictOrderedRing 𝕜] {m₁ m₂ : ℕ}

omit [IsStrictOrderedRing 𝕜] in
/-- **`Ξ`-membership from the two sides.** Given rough-factor data on each side of the modulus —
every entry in `[δ, 1]`, and each side's sum under its own cap — the pooled tuple lies in
`Ξ(B₁, B₂, m₁, m₂, δ)`.

This is the interface the factor-extraction lemmas use to reach the packing conditions. -/
theorem mem_Xi_append {B₁ B₂ δ : 𝕜} (u : Fin m₁ → 𝕜) (v : Fin m₂ → 𝕜)
    (hu : ∀ i, u i ∈ Set.Icc δ 1) (hv : ∀ i, v i ∈ Set.Icc δ 1)
    (hsu : ∑ i, u i ≤ B₁) (hsv : ∑ i, v i ≤ B₂) :
    Fin.append u v ∈ Xi B₁ B₂ m₁ m₂ δ := by
  refine ⟨append_mem_of_mem u v hu hv, ?_, ?_⟩
  · rw [sum_filter_append_left]; exact hsu
  · rw [sum_filter_append_right]; exact hsv

end Xi

end Gap212.Packing
