/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public meta import Gap212.Attr
public import Gap212.Main
public import Gap212.Routing.Defs.Equidistribution

/-!
# Extracting factors from a generated modulus

A modulus generated by a support is bounded by the product of the two mixed caps of `Gap212.Qgen`:
writing `q = e e' ∏ fᵢ ∏ f'ᵢ` as `(e ∏ fᵢ) * (e' ∏ f'ᵢ)` puts each factor under one of them, and
the enlargement `ε` subtracted on the unprimed side cancels the `ε` added on the primed one — the
asymmetry of the pair is what makes the resulting exponent symmetric in `j, j'`:

`q ≤ x ^ ((1 - ε₀) * (A_j + A_{j'}))`.

That cap holds for every retreat `ε₀`, and it degenerates at `ε₀ ≥ 1`: there `1 - ε₀ ≤ 0`, so a
nonnegative sum of band endpoints makes the exponent nonpositive, and for `x ≥ 1` the cap itself is
at most `1`. Since `Qgen` also asks `1 ≤ q`, the only modulus a retreat of one or more generates
is `q = 1`.

At the modulus `1` the unrestricted discrepancy vanishes identically: both `finsum`s of
`Gap212.sumError` run over all of `ℕ` — every natural is congruent to `a` modulo `1` and coprime to
`1` — and `φ 1 = 1`, so the two are the same expression and their difference is `0`. No summability
hypothesis on `f` enters, the sums being equal whatever value they take.

Together these make the equidistribution machinery vacuous at a retreat of one or more: the
discrepancy sum over any family of generated moduli is `0`, so every bound asserted of it holds.
That is what licenses the arguments further into the section to assume `ε₀ ∈ (0, 1)`, the range on
which `1 - ε₀` is positive and may be divided by.

## Main results

* `Gap212.Qgen_subset_one_and_sumError_eq_zero_of_one_le_retreat`: at `ε₀ ≥ 1` the generated family
  is contained in `{1}`, the discrepancy at the modulus `1` vanishes for every sequence and every
  residue, and hence so does the discrepancy sum over any finite family of generated moduli.

## Implementation notes

Two hypotheses are weaker than in [2], in each case because the proof does not use the
strictness: `1 ≤ x`, the base entering only to turn a nonpositive exponent into a cap of at most
`1`, and `0 ≤ A_j + A_{j'}`, that sum being multiplied by the nonpositive `1 - ε₀`. At `x = 1`
every cap is `1` and the conclusion still holds. The band endpoint `A_j` of [2, Definition 2] is
`p.A j.succ`, strata being indexed by `Fin p.n`.

The three assertions are conjoined because they are one move, the reduction to `ε₀ < 1`. The first
is the containment `Qgen p x j j' m m' ε₀ ⊆ {1}` rather than "no `q > 1` is generated": the two
differ only at `q = 0`, which `Qgen` excludes through its own `1 ≤ q`, and the containment is the
form a consumer rewrites with. The third is an equality with `0` rather than an inequality against
a bound, which is what makes every asserted bound with a nonnegative right-hand side follow, with
no side condition on that bound's constants.

The containment is not an equality in general: the factorization of `1` forces `e ∏ fᵢ = 1`, so
`1 ∈ Qgen p x j j' m m' ε₀` requires `1 ≤ x ^ ((1 - ε₀) * (A_j - ε))`, which for `x > 1` at a
retreat `ε₀ > 1` asks `A_j ≤ ε`. It *is* an equality at both boundaries this file admits. At
`ε₀ = 1` every cap has exponent `0` and so reads `_ ≤ 1`, which `e = e' = 1`, `m = m' = 0` meets.
At `x = 1` the forward inclusion needs no cap at all: `Qgen` carries both `1 ≤ q` and
`(q : ℝ) ≤ x`, and `le_antisymm` on those two pins `q = 1`.

Membership in `Qgen` is read only through the two projections `one_le_of_mem_Qgen` and
`le_rpow_of_mem_Qgen`, so no proof below destructures the definition. The mixed-cap product is the
second of those, and the same product is asserted as `Gap212.Extraction.qgen_le` under the strict
hypothesis `1 < x`. That strictness excludes the boundary `x = 1` reached here, which is why the
cap is reproved privately under `0 < x` rather than imported.

## References

* [2, Definition 2] for the generated moduli and their caps, and [2, Definition 3] for the
  discrepancy sum.
-/

public section

namespace Gap212

variable {p : SupportParams} {x ε₀ : ℝ} {j j' : Fin p.n} {m m' : ℕ}

/-- A generated modulus is at least `1`, `Qgen` asking it of every member. -/
private lemma one_le_of_mem_Qgen {q : ℕ} (hq : q ∈ Qgen p x j j' m m' ε₀) : 1 ≤ q := by
  obtain ⟨-, -, -, -, -, hq1, -⟩ := hq
  exact hq1

/-- **The two mixed caps of `Qgen` multiply, and the enlargement cancels**: a generated modulus
satisfies `q ≤ x ^ ((1 - ε₀) * (A_j + A_{j'}))`, for every retreat `ε₀` and every positive base.
The base enters only through `Real.rpow_add` and the nonnegativity of the two caps, so `0 < x` is
enough; in particular the boundary `x = 1`, where both caps read `_ ≤ 1`, is covered. -/
private lemma le_rpow_of_mem_Qgen {q : ℕ} (hx : 0 < x) (hq : q ∈ Qgen p x j j' m m' ε₀) :
    (q : ℝ) ≤ x ^ ((1 - ε₀) * (p.A j.succ + p.A j'.succ)) := by
  obtain ⟨e, e', f, f', rfl, -, -, -, -, hcap, hcap', -, -, -⟩ := hq
  calc ((e * e' * (∏ i, f i) * (∏ i, f' i) : ℕ) : ℝ)
      = ((e * ∏ i, f i : ℕ) : ℝ) * ((e' * ∏ i, f' i : ℕ) : ℝ) := by push_cast; ring
    _ ≤ x ^ ((1 - ε₀) * (p.A j.succ - p.ε)) * x ^ ((1 - ε₀) * (p.A j'.succ + p.ε)) :=
        mul_le_mul hcap hcap' (by positivity) (by positivity)
    _ = x ^ ((1 - ε₀) * (p.A j.succ + p.A j'.succ)) := by
        rw [← Real.rpow_add hx]; ring_nf

/-- At a retreat `ε₀ ≥ 1` with band endpoints summing to something nonnegative, the only modulus
the generated family can produce is `1`: its cap has nonpositive exponent, hence is at most `1`,
while `Qgen` asks `1 ≤ q`. -/
private lemma Qgen_subset_one_of_one_le_retreat (hx : 1 ≤ x) (hε₀ : 1 ≤ ε₀)
    (hA : 0 ≤ p.A j.succ + p.A j'.succ) : Qgen p x j j' m m' ε₀ ⊆ {1} := fun _ hq =>
  Set.mem_singleton_iff.2 <| le_antisymm
    (Nat.cast_le_one.1 <| (le_rpow_of_mem_Qgen (zero_lt_one.trans_le hx) hq).trans <|
      Real.rpow_le_one_of_one_le_of_nonpos hx <|
        mul_nonpos_of_nonpos_of_nonneg (sub_nonpos.2 hε₀) hA)
    (one_le_of_mem_Qgen hq)

/-- The unrestricted discrepancy at the modulus `1` vanishes, for every sequence and every residue:
both of its sums run over all of `ℕ` and `φ 1 = 1`, so they are the same expression. -/
private lemma sumError_one_eq_zero (f : ℕ → ℂ) (a : ℕ) : sumError f 1 a = 0 := by
  simp [sumError, Nat.modEq_one]

/-- **A retreat at or above one is degenerate.** Let `ε₀ ≥ 1`, let `x ≥ 1`, and suppose the two
band endpoints satisfy `0 ≤ A_j + A_{j'}`. Then the generated family
`Q_gen(p, x, j, j', m, m', ε₀)` is contained in `{1}`; the discrepancy `Δ(f; 1, a)` vanishes for
every sequence `f` and every residue `a`; and consequently the discrepancy sum over any finite
family of generated moduli vanishes, so every bound asserted of it holds trivially. -/
@[gap212 "lem_retreat_degenerate"]
theorem Qgen_subset_one_and_sumError_eq_zero_of_one_le_retreat
    (hx : 1 ≤ x) (hε₀ : 1 ≤ ε₀) (hA : 0 ≤ p.A j.succ + p.A j'.succ) :
    Qgen p x j j' m m' ε₀ ⊆ {1} ∧
      (∀ (f : ℕ → ℂ) (a : ℕ), sumError f 1 a = 0) ∧
      ∀ (f : ℕ → ℂ) (a : ℕ) (D : Finset ℕ), ↑D ⊆ Qgen p x j j' m m' ε₀ →
        ∑ q ∈ D, ‖sumError f q a‖ = 0 := by
  have hsub : Qgen p x j j' m m' ε₀ ⊆ {1} := Qgen_subset_one_of_one_le_retreat hx hε₀ hA
  refine ⟨hsub, sumError_one_eq_zero, fun f a D hD => Finset.sum_eq_zero fun q hq => ?_⟩
  rw [Set.eq_of_mem_singleton (hsub (hD hq)), sumError_one_eq_zero, norm_zero]

end Gap212
