/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Gap212.Extraction.Setup
public meta import Gap212.Attr

/-!
# Four-factor extraction

The third and most delicate factor-extraction lemma, and the one the Type IIc estimate
needs. Beyond the factorization `q = u v r` of three-factor extraction, a *nested* divisor is
wanted:
`d₁ ∣ r` lying in `[R² x^{a₃}, R² x^{b₃}]` — and not for one `R`, but for **every** `R` in the
first window `[x^{a₁}, x^{b₁}]`.

## Why this one is stated on a dyadic block

The available capacities depend on the actual size of `q`, through the third block's bound
`1/2 + 2ω₀ - b₁ - a₂`. So the lemma is stated for `q ≍ x^{1/2 + 2ω₀}` rather than replacing `ω₀` by
a global maximum at the outset. Only the lower half of that is used, so the hypothesis here is the
lower bound.

## The three draws

`Gap212.Extraction.xi_of_qgen` supplies the reservoir and pooled tuple; the four-block packing
condition returns `I₁`, `I₂`, `I₃` with the complement playing `I₄`, and capacities

    ∑_{I₁} yᵢ ≤ 2a₁ + b₃,   ∑_{I₂} yᵢ ≤ b₂,
    ∑_{I₃} yᵢ ≤ 1/2 + 2ω₀ - b₁ - a₂,   ∑_{I₄} yᵢ ≤ a₁ - 2b₁ - a₃.

Writing `Rₖ` for the product of `F` over `Iₖ`:

1. `u` is drawn from `R₂` and the reservoir, landing in `[x^{a₂}, x^{b₂}]`;
2. `r` is drawn from `R₁ · R₄` and what remains of the reservoir, landing in `[x^{a₁}, x^{b₁}]`;
3. `d₁` is drawn from `R₁` and the part of the reservoir that draw 2 consumed, landing in
   `[x^{2c+a₃}, x^{2c+b₃}]` for whichever `c` is asked for.

Draw 3 divides `r` because `R₁ ∣ R₁ · R₄` and its reservoir part divides the one draw 2 used. This
is why the witness form `exists_divisor_window_witness` is needed rather than the bare existence
statement: draw 3 reaches back into draw 2's consumption.

## Where `3(b₁ - a₁) + (a₃ - b₃) ≥ 0` is used — twice

This is the least transparent hypothesis of the lemma, and it does two separate jobs.

First, it is what makes `R₁ · R₄` fit under `x^{b₁}` at all: the two capacities add to
`3a₁ - 2b₁ + b₃ - a₃`, and that is `≤ b₁` exactly when `3(b₁ - a₁) + (a₃ - b₃) ≥ 0`.

Second, it is the slack that makes draw 1 possible. Dropping `I₁`, `I₃` and `I₄` from `log_x q`
leaves `a₂ + [3(b₁ - a₁) + (a₃ - b₃)]`, so the hypothesis is precisely the statement that this is
still at least `a₂`.

## Capacity positivity comes for free

The four capacities must each be nonnegative for the packing condition to be satisfiable at all —
a block's `y`-sum is a sum of nonnegative terms. So rather than assuming `0 ≤ a₁ - 2b₁ - a₃` and
its companions, they are *derived* from the partition the condition hands over.

## Main results

* `Gap212.Extraction.four_factor`: the lemma.
-/

@[expose] public section

namespace Gap212.Extraction

open Finset Real Gap212.Packing

set_option maxHeartbeats 1000000 in
-- Three nested draws, each with its own size and capacity bookkeeping, in a single proof: the
-- default heartbeat budget is not enough to elaborate it.
/-- **Four-factor extraction.** Under the four-block packing condition, every `q` generated by the
support with `q ≥ x^{1/2 + 2ω₀ - ε₀(1/2 + 2ω₀ - b₁ - a₂)}` factors as `q = u v r` with
`u ∈ [x^{a₂}, x^{b₂}]` and `r ∈ [x^{a₁}, x^{b₁}]`, and moreover for **every** `c ∈ [a₁, b₁]` the
factor `r` has a divisor in `[x^{2c+a₃}, x^{2c+b₃}]`. -/
@[gap212 "lem_partition3"]
theorem four_factor {p : SupportParams} {x ε₀ a₁ b₁ a₂ b₂ a₃ b₃ ω₀ : ℝ}
    {j j' : Fin p.n} {m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hδ : 0 < p.δ) (hε₀ : 0 < ε₀) (hε₀1 : ε₀ < 1)
    (hw₁ : a₁ + p.δ ≤ b₁) (hw₂ : a₂ + p.δ ≤ b₂) (hw₃ : a₃ + p.δ ≤ b₃)
    (hstep : a₁ - a₂ ≤ b₁ - b₂)
    (hnest : 0 ≤ 3 * (b₁ - a₁) + (a₃ - b₃))
    (hB : p.B j m ≤ 1) (hB' : p.B j' m' ≤ 1)
    (hpack : ∀ y ∈ Xi (p.B j m) (p.B j' m') m m' p.δ,
      AdmitsPartition₄ y (2 * a₁ + b₃) b₂ (1 / 2 + 2 * ω₀ - b₁ - a₂) (a₁ - 2 * b₁ - a₃))
    (hq : q ∈ Qgen p x j j' m m' ε₀)
    (hqbig : x ^ (1 / 2 + 2 * ω₀ - ε₀ * (1 / 2 + 2 * ω₀ - b₁ - a₂)) ≤ (q : ℝ)) :
    ∃ u r : ℕ, u * r ∣ q ∧
      x ^ a₂ ≤ (u : ℝ) ∧ (u : ℝ) ≤ x ^ b₂ ∧
      x ^ a₁ ≤ (r : ℝ) ∧ (r : ℝ) ≤ x ^ b₁ ∧
      ∀ c : ℝ, a₁ ≤ c → c ≤ b₁ →
        ∃ d₁, d₁ ∣ r ∧ x ^ (2 * c + a₃) ≤ (d₁ : ℝ) ∧ (d₁ : ℝ) ≤ x ^ (2 * c + b₃) := by
  classical
  obtain ⟨S, F, y, hq1, hS1, hsm, hF1, hqF, hmem, hlogF, hynn⟩ :=
    xi_of_qgen hx hδ hε₀ hε₀1 hB hB' hq
  obtain ⟨I₁, I₂, I₃, h12, h13, h23, hc₁, hc₂, hc₃, hc₄⟩ := hpack _ hmem
  have hx0 : (0 : ℝ) < x := by linarith
  have hprodF1 : 1 ≤ ∏ i, F i := Finset.one_le_prod' fun i _ ↦ hF1 i
  set I₄ : Finset (Fin (m + m')) := univ \ (I₁ ∪ I₂ ∪ I₃)
  set R₁ : ℕ := ∏ i ∈ I₁, F i with hR₁_def
  set R₂ : ℕ := ∏ i ∈ I₂, F i with hR₂_def
  set R₄ : ℕ := ∏ i ∈ I₄, F i with hR₄_def
  have hR₁1 : 1 ≤ R₁ := Finset.one_le_prod' fun i _ ↦ hF1 i
  have hR₂1 : 1 ≤ R₂ := Finset.one_le_prod' fun i _ ↦ hF1 i
  have hR₄1 : 1 ≤ R₄ := Finset.one_le_prod' fun i _ ↦ hF1 i
  have hblock : ∀ J : Finset (Fin (m + m')), ∑ i ∈ J, logb x (F i) = (1 - ε₀) * ∑ i ∈ J, y i :=
    fun J ↦ by rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
  have hblocknn : ∀ J : Finset (Fin (m + m')), 0 ≤ ∑ i ∈ J, y i :=
    fun J ↦ Finset.sum_nonneg fun i _ ↦ hynn i
  -- Capacity positivity, from the partition itself.
  have hp₁ : 0 ≤ 2 * a₁ + b₃ := le_trans (hblocknn I₁) hc₁
  have hp₄ : 0 ≤ a₁ - 2 * b₁ - a₃ := le_trans (hblocknn I₄) hc₄
  have hb₂0 : 0 ≤ b₂ := le_trans (hblocknn I₂) hc₂
  -- Block products under their capacities.
  have hcap : ∀ (J : Finset (Fin (m + m'))) (c : ℝ), ∑ i ∈ J, y i ≤ c → 0 ≤ c →
      ((∏ i ∈ J, F i : ℕ) : ℝ) ≤ x ^ c := by
    intro J c hJ hc0
    refine prod_le_rpow_of_sum_le hx J F (fun i _ ↦ hF1 i) ?_
    rw [hblock J]
    nlinarith [mul_nonneg hε₀.le (hblocknn J)]
  have hR₁cap : (R₁ : ℝ) ≤ x ^ (2 * a₁ + b₃) := hcap I₁ _ hc₁ hp₁
  have hR₂cap : (R₂ : ℝ) ≤ x ^ b₂ := hcap I₂ _ hc₂ hb₂0
  have hR₄cap : (R₄ : ℝ) ≤ x ^ (a₁ - 2 * b₁ - a₃) := hcap I₄ _ hc₄ hp₄
  -- `R₁ · R₄ ≤ x^{b₁}`: this is the first use of the nesting hypothesis.
  have hR₁₄1 : 1 ≤ R₁ * R₄ := one_le_mul hR₁1 hR₄1
  have hR₁₄cap : ((R₁ * R₄ : ℕ) : ℝ) ≤ x ^ b₁ := by
    rw [Nat.cast_mul]
    calc (R₁ : ℝ) * R₄ ≤ x ^ (2 * a₁ + b₃ + (a₁ - 2 * b₁ - a₃)) := by
          rw [rpow_add hx0]; gcongr
      _ ≤ x ^ b₁ := rpow_le_rpow_of_exponent_le hx.le (by linarith)
  -- Disjointness and the sum decomposition.
  have hdisj124 : Disjoint (I₁ ∪ I₂) I₄ := disjoint_sdiff.mono_left subset_union_left
  have hU : (∑ i ∈ I₁ ∪ I₂ ∪ I₃, logb x (F i)) + ∑ i ∈ I₄, logb x (F i)
      = ∑ i, logb x (F i) := Finset.sum_add_sum_compl _ _
  have hU3 : ∑ i ∈ I₁ ∪ I₂ ∪ I₃, logb x (F i)
      = (∑ i ∈ I₁, logb x (F i)) + (∑ i ∈ I₂, logb x (F i)) + ∑ i ∈ I₃, logb x (F i) := by
    rw [Finset.sum_union (disjoint_union_left.2 ⟨h13, h23⟩), Finset.sum_union h12]
  -- The modulus contains `R₁ · R₄ · R₂ · S`.
  have hprod124 : (R₁ * R₄) * R₂ = ∏ i ∈ (I₁ ∪ I₂) ∪ I₄, F i := by
    rw [Finset.prod_union hdisj124, Finset.prod_union h12, ← hR₁_def, ← hR₂_def, ← hR₄_def]
    ring
  have hdvd : (R₁ * R₄) * R₂ * S ∣ q := by
    rw [hqF, hprod124]
    exact mul_dvd_mul_right (prod_subset_dvd_prod (Finset.subset_univ _) F) S
  -- Logarithmic bookkeeping.
  have hlogq : logb x (q : ℝ) = ∑ i, logb x (F i) + logb x (S : ℝ) := by
    rw [hqF, logb_mul_nat hprodF1 hS1, logb_prod_nat univ F fun i _ ↦ hF1 i]
  set C₃ : ℝ := 1 / 2 + 2 * ω₀ - b₁ - a₂ with hC₃_def
  have hlogqbig : 1 / 2 + 2 * ω₀ - ε₀ * C₃ ≤ logb x (q : ℝ) := le_logb_of_rpow_le hx hq1 hqbig
  have hthird : (1 - ε₀) * (∑ i ∈ I₃, y i) ≤ (1 - ε₀) * C₃ :=
    mul_le_mul_of_nonneg_left hc₃ (by linarith)
  have hone : (1 - ε₀) * (∑ i ∈ I₁, y i) ≤ 2 * a₁ + b₃ := by
    nlinarith [mul_nonneg hε₀.le (hblocknn I₁)]
  have hfour : (1 - ε₀) * (∑ i ∈ I₄, y i) ≤ a₁ - 2 * b₁ - a₃ := by
    nlinarith [mul_nonneg hε₀.le (hblocknn I₄)]
  -- Draw 1: `u = R₂ · s₂`, using the nesting hypothesis a second time.
  have hbig₂ : x ^ a₂ ≤ ((R₂ * S : ℕ) : ℝ) := by
    refine rpow_le_of_le_logb hx (one_le_mul hR₂1 hS1) ?_
    rw [logb_mul_nat hR₂1 hS1, hR₂_def, logb_prod_nat I₂ F fun i _ ↦ hF1 i]
    linarith [hlogq, hlogqbig, hU, hU3, hblock I₁, hblock I₃, hblock I₄,
      hthird, hone, hfour]
  obtain ⟨s₂, hs₂S, hu1, hu2⟩ :=
    exists_divisor_window_witness hx hR₂1 hS1 hR₂cap (fun r hr hd ↦ (hsm r hr hd).le) hbig₂
      (by linarith)
  -- What remains of the reservoir.
  have hs₂0 : s₂ ≠ 0 := ne_zero_of_dvd_ne_zero (by lia) hs₂S
  have hST : s₂ * (S / s₂) = S := Nat.mul_div_cancel' hs₂S
  have hT1 : 1 ≤ S / s₂ := Nat.div_pos (Nat.le_of_dvd (by lia) hs₂S) (Nat.pos_of_ne_zero hs₂0)
  have hTsm : ∀ r : ℕ, r.Prime → r ∣ (S / s₂) → (r : ℝ) ≤ x ^ p.δ := fun r hr hrT ↦
    (hsm r hr (dvd_trans hrT (Nat.div_dvd_of_dvd hs₂S))).le
  -- Draw 2: `r = (R₁ · R₄) · s₁` from what is left.
  have hbig₁ : x ^ (a₁ + b₂) ≤ (((R₁ * R₄) * R₂ * S : ℕ) : ℝ) := by
    have h124 : 1 ≤ (R₁ * R₄) * R₂ := one_le_mul hR₁₄1 hR₂1
    refine rpow_le_of_le_logb hx (one_le_mul h124 hS1) ?_
    rw [logb_mul_nat h124 hS1, hprod124,
      logb_prod_nat _ F fun i _ ↦ hF1 i, Finset.sum_union hdisj124, Finset.sum_union h12]
    linarith [hlogq, hlogqbig, hU, hU3, hblock I₃, hthird]
  have hupos : (0 : ℝ) < ((R₂ * s₂ : ℕ) : ℝ) :=
    Nat.cast_pos.2 (Nat.pos_of_ne_zero (Nat.mul_ne_zero (by lia) hs₂0))
  have hbigT : x ^ a₁ ≤ (((R₁ * R₄) * (S / s₂) : ℕ) : ℝ) := by
    refine le_of_mul_le_mul_right ?_ hupos
    calc x ^ a₁ * ((R₂ * s₂ : ℕ) : ℝ) ≤ x ^ (a₁ + b₂) := by rw [rpow_add hx0]; gcongr
      _ ≤ (((R₁ * R₄) * R₂ * S : ℕ) : ℝ) := hbig₁
      _ = _ := by
        conv_lhs => rw [← hST]
        push_cast
        ring
  obtain ⟨s₁, hs₁T, hr1, hr2⟩ :=
    exists_divisor_window_witness hx hR₁₄1 hT1 hR₁₄cap hTsm hbigT (by linarith)
  -- Assemble.
  refine ⟨R₂ * s₂, (R₁ * R₄) * s₁, ?_, hu1, hu2, hr1, hr2, ?_⟩
  · -- `u · r ∣ q`, since the two reservoir draws are disjoint.
    obtain ⟨c, hc⟩ := hs₁T
    refine dvd_trans ⟨c, ?_⟩ hdvd
    rw [← hST, hc]
    ring
  · -- Draw 3: the nested divisor, for every `c` in the first window.
    intro c hc1 hc2
    have hs₁1 : 1 ≤ s₁ := Nat.pos_of_dvd_of_pos hs₁T hT1
    have hs₁sm : ∀ r : ℕ, r.Prime → r ∣ s₁ → (r : ℝ) ≤ x ^ p.δ := fun r hr hrs ↦
      hTsm r hr (dvd_trans hrs hs₁T)
    -- `R₁ ≤ x^{2c + b₃}`, since `c ≥ a₁`.
    have hR₁c : (R₁ : ℝ) ≤ x ^ (2 * c + b₃) :=
      hR₁cap.trans (rpow_le_rpow_of_exponent_le hx.le (by linarith))
    -- `x^{2c + a₃} ≤ R₁ · s₁`: divide `r ≥ x^{a₁}` by `R₄ ≤ x^{a₁ - 2b₁ - a₃}`.
    have hbig₃ : x ^ (2 * c + a₃) ≤ ((R₁ * s₁ : ℕ) : ℝ) := by
      refine le_of_mul_le_mul_right ?_ (Nat.cast_pos.2 hR₄1 : (0 : ℝ) < R₄)
      calc x ^ (2 * c + a₃) * R₄ ≤ x ^ (2 * c + a₃ + (a₁ - 2 * b₁ - a₃)) := by
            rw [rpow_add hx0 (2 * c + a₃)]; gcongr
        _ ≤ x ^ a₁ := rpow_le_rpow_of_exponent_le hx.le (by linarith)
        _ ≤ (((R₁ * R₄) * s₁ : ℕ) : ℝ) := hr1
        _ = _ := by push_cast; ring
    obtain ⟨s', hs'dvd, hd1, hd2⟩ :=
      exists_divisor_window_witness hx hR₁1 hs₁1 hR₁c hs₁sm hbig₃ (by linarith)
    -- `R₁ · s' ∣ (R₁ · R₄) · s₁`, since `s' ∣ s₁`.
    exact ⟨R₁ * s', mul_dvd_mul (dvd_mul_right R₁ R₄) hs'dvd, hd1, hd2⟩

end Gap212.Extraction
