/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Gap212.Main
public import Gap212.Packing.Append
public import Gap212.Packing.Divisors
public import Gap212.Packing.LogBridge
public meta import Gap212.Attr

/-!
# From a generated modulus to a `Ξ`-tuple

All three factor-extraction lemmas open the same way. A modulus `q` generated by the
support is unpacked as `q = e e' ∏ fᵢ ∏ f'ᵢ`; the rough factors are pooled and rescaled to
`yᵢ = log_x(fᵢ)/(1-ε₀)`; and the `Q`-caps and roughness conditions are shown to place that pooled
tuple in `Ξ`, so the packing condition applies. Only afterwards do the three lemmas diverge, in how
many blocks they ask for and which windows they aim at.

This module does that opening once. `xi_of_qgen` returns everything the three lemmas need:

* the positivity of `q` itself;
* the smooth reservoir `S = e e'`, positive and `x^δ`-smooth, the bound on its primes being
  **strict** as `Gap212.Qgen` states it — which is what an open divisor window needs;
* the pooled rough factors `F`, all at least `1`, with `q = (∏ F) · S`;
* the pooled rescaled logarithms `y`, lying in `Ξ`, nonnegative, and satisfying
  `log_x (F i) = (1 - ε₀) · y i` — the identity that turns a bound on a block of `y` into a bound
  on the corresponding product of factors.

## Why the caps `B ≤ 1` are hypotheses

`Ξ` confines its tuples to `[δ, 1]`, and `SupportParams` bounds `B` below (by `δ`) but not above.
The entrywise upper bound `yᵢ ≤ 1` must therefore come from the *sum* bound on `yᵢ`'s own side,
which needs that side's cap to be at most `1`. Every cap of `Gap212.gap212Cap` is at most
`1081/5000`, so this is harmless, but it is a genuine hypothesis rather than a triviality.

## Main results

* `Gap212.Extraction.xi_of_qgen`: the shared opening.
* `Gap212.Extraction.qgen_le`: generated moduli are at most `x^{(1-ε₀)(A_j + A_{j'})}`.
-/

@[expose] public section

namespace Gap212.Extraction

open Finset Real Gap212.Packing

/-- **The shared opening of the factor-extraction lemmas.** A modulus generated by the support
yields a smooth reservoir, a pooled tuple of rough factors, and a pooled tuple of rescaled
logarithms lying in `Ξ`. -/
@[gap212 "lem_rough_profile_in_xi"]
theorem xi_of_qgen {p : SupportParams} {x ε₀ : ℝ} {j j' : Fin p.n} {m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hδ : 0 < p.δ) (hε₀ : 0 < ε₀) (hε₀1 : ε₀ < 1)
    (hB : p.B j m ≤ 1) (hB' : p.B j' m' ≤ 1)
    (hq : q ∈ Qgen p x j j' m m' ε₀) :
    ∃ (S : ℕ) (F : Fin (m + m') → ℕ) (y : Fin (m + m') → ℝ),
      1 ≤ q ∧
      1 ≤ S ∧
      (∀ r : ℕ, r.Prime → r ∣ S → (r : ℝ) < x ^ p.δ) ∧
      (∀ i, 1 ≤ F i) ∧
      q = (∏ i, F i) * S ∧
      y ∈ Xi (p.B j m) (p.B j' m') m m' p.δ ∧
      (∀ i, logb x (F i) = (1 - ε₀) * y i) ∧
      (∀ i, 0 ≤ y i) := by
  classical
  obtain ⟨e, e', f, f', hqeq, hq1, -, hfcap, hf'cap, -, -, hsm, hfr, hf'r⟩ := hq
  have hden : (0 : ℝ) < 1 - ε₀ := by linarith
  -- Every rough factor exceeds `x^δ > 1`, hence is at least `1`.
  have hxδ1 : 1 < x ^ p.δ := Real.one_lt_rpow hx hδ
  have hf1 : ∀ i, 1 ≤ f i := fun i ↦ by exact_mod_cast (hxδ1.trans_le (hfr i)).le
  have hf'1 : ∀ i, 1 ≤ f' i := fun i ↦ by exact_mod_cast (hxδ1.trans_le (hf'r i)).le
  -- The smooth part is nonzero, since `q` is.
  have he1 : 1 ≤ e := Nat.pos_of_ne_zero fun h ↦ by simp_all
  have he'1 : 1 ≤ e' := Nat.pos_of_ne_zero fun h ↦ by simp_all
  -- The scaled logarithms on each side.
  set u : Fin m → ℝ := fun i ↦ logb x (f i) / (1 - ε₀) with hu_def
  set v : Fin m' → ℝ := fun i ↦ logb x (f' i) / (1 - ε₀) with hv_def
  have hsumu : ∑ i, u i ≤ p.B j m := by
    rw [hu_def, ← Finset.sum_div, div_le_iff₀ hden]
    linarith [sum_logb_le_of_prod_le hx univ f (fun i _ ↦ hf1 i) hfcap]
  have hsumv : ∑ i, v i ≤ p.B j' m' := by
    rw [hv_def, ← Finset.sum_div, div_le_iff₀ hden]
    linarith [sum_logb_le_of_prod_le hx univ f' (fun i _ ↦ hf'1 i) hf'cap]
  have hu_lb : ∀ i, p.δ ≤ u i := fun i ↦ by
    have h := le_logb_of_rpow_le hx (hf1 i) (hfr i)
    rw [hu_def, le_div_iff₀ hden]
    nlinarith [mul_nonneg hδ.le hε₀.le]
  have hv_lb : ∀ i, p.δ ≤ v i := fun i ↦ by
    have h := le_logb_of_rpow_le hx (hf'1 i) (hf'r i)
    rw [hv_def, le_div_iff₀ hden]
    nlinarith [mul_nonneg hδ.le hε₀.le]
  have hu_ub : ∀ i, u i ≤ 1 := fun i ↦
    ((single_le_sum (fun k _ ↦ hδ.le.trans (hu_lb k)) (mem_univ i)).trans hsumu).trans hB
  have hv_ub : ∀ i, v i ≤ 1 := fun i ↦
    ((single_le_sum (fun k _ ↦ hδ.le.trans (hv_lb k)) (mem_univ i)).trans hsumv).trans hB'
  -- Package it. `Qgen`'s smooth clause is strict (`r < x ^ δ`)
  -- and is passed on strict: the open windows of the modulus families need that strictness, and a
  -- consumer wanting only `≤` weakens it at its own call site.
  refine ⟨e * e', Fin.append f f', Fin.append u v, hq1, ?_,
    hsm, ?_, ?_, ?_, ?_, ?_⟩
  · simpa using Nat.mul_le_mul he1 he'1
  · exact fun i ↦ append_mem_of_mem (S := {n : ℕ | 1 ≤ n}) f f' hf1 hf'1 i
  · simp only [hqeq, Fin.prod_univ_add, Fin.append_left, Fin.append_right]; ring
  · exact mem_Xi_append u v (fun i ↦ ⟨hu_lb i, hu_ub i⟩) (fun i ↦ ⟨hv_lb i, hv_ub i⟩) hsumu hsumv
  · intro i
    induction i using Fin.addCases with
    | left i => simp only [hu_def, Fin.append_left]; field_simp
    | right i => simp only [hv_def, Fin.append_right]; field_simp
  · exact fun i ↦ append_mem_of_mem (S := {t : ℝ | 0 ≤ t}) u v
      (fun i ↦ le_trans hδ.le (hu_lb i)) (fun i ↦ le_trans hδ.le (hv_lb i)) i

/-- **Generated moduli are small.** A modulus generated at `(j, j')` satisfies
`q ≤ x^{(1-ε₀)(A_j + A_{j'})}`.

The two mixed caps of `Qgen` multiply: `e ∏ fᵢ ≤ x^{(1-ε₀)(A_j - ε)}` and
`e' ∏ f'ᵢ ≤ x^{(1-ε₀)(A_{j'} + ε)}`, and the `ε` cancels between them. This is what places the
generated moduli inside `moduliRange x ω` at `ω = (A_j + A_{j'})/2 - 1/4`, which is the `ω_max` of
[2] — so the asymmetry of the two caps is exactly what makes the level come out symmetric. -/
@[gap212 "lem_modulus_size_bound"] theorem qgen_le {p : SupportParams} {x ε₀ : ℝ} {j j' : Fin p.n}
{m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hq : q ∈ Qgen p x j j' m m' ε₀) :
    (q : ℝ) ≤ x ^ ((1 - ε₀) * (p.A j.succ + p.A j'.succ)) := by
  obtain ⟨e, e', f, f', hqeq, -, -, -, -, hAcap, hA'cap, -, -, -⟩ := hq
  calc (q : ℝ) = ((e * ∏ i, f i : ℕ) : ℝ) * ((e' * ∏ i, f' i : ℕ) : ℝ) := by
        rw [hqeq]; push_cast; ring
    _ ≤ x ^ ((1 - ε₀) * (p.A j.succ - p.ε)) * x ^ ((1 - ε₀) * (p.A j'.succ + p.ε)) :=
        mul_le_mul hAcap hA'cap (by positivity) (by positivity)
    _ = x ^ ((1 - ε₀) * (p.A j.succ + p.A j'.succ)) := by
        rw [← Real.rpow_add (by linarith)]; ring_nf

end Gap212.Extraction
