/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Gap212.Extraction.Setup
public meta import Gap212.Attr

/-!
# Three-factor extraction

The second factor-extraction lemma. Now two divisors are wanted *simultaneously*: a
factorization `q = u v r` with `r ∈ [x^{a₁}, x^{b₁}]` and `u ∈ [x^{a₂}, x^{b₂}]`. Three rough
blocks reserve mass for `r`, for `u`, and for the unconstrained remainder.

## The argument

`Gap212.Extraction.xi_of_qgen` supplies the reservoir and the pooled tuple as before, and the
three-block packing condition returns blocks `I₁`, `I₂` with

    ∑_{I₁} yᵢ ≤ b₁,     ∑_{I₂} yᵢ ≤ b₂,     ∑_{rest} yᵢ ≤ 1/2 - b₁ - a₂.

Set `R₁ = ∏_{I₁} Fᵢ` and `R₂ = ∏_{I₂} Fᵢ`. Then `Gap212.Packing.exists_two_divisors_window` draws
twice from the one reservoir, the second draw avoiding the primes the first consumed.

## Where `b₁ - b₂ ≥ a₁ - a₂` is used

This is the hypothesis that looks unmotivated in the statement. The two-draw lemma needs

    x^{a₁ + b₂} ≤ R₁ · R₂ · S,

the `b₂` being the price already paid by the first draw. Unwinding, `log_x(R₁ R₂ S)` is at least

    (1/2 - ε₁) - (1-ε₀)(1/2 - b₁ - a₂)  =  b₁ + a₂ - ε₁ + ε₀(1/2 - b₁ - a₂),

so what is needed is `a₁ + b₂ ≤ b₁ + a₂`, i.e. exactly `b₁ - b₂ ≥ a₁ - a₂`. The condition is not a
technical convenience: it is the statement that the second window is reachable after the first has
been served.

The third block's capacity `1/2 - b₁ - a₂` carries no positivity hypothesis of its own; it
enters only through the packing condition.

## `ε₁`, again explicit

`ε₁ = ε₀(1/2 - b₁ - a₂)` works here, by the same computation. As in two-factor extraction [2]
leaves it existential; naming it keeps the six routes of the routing argument commensurable.

## Main results

* `Gap212.Extraction.three_factor`: the lemma.
* `Gap212.Extraction.three_factor_strict`: the same with both windows **open**, paid for by the
  retreat at the top ends and by a threshold `ε₁` strictly below `ε₀(1/2 - b₁ - a₂)` at the bottom.
-/

@[expose] public section

namespace Gap212.Extraction

open Finset Real Gap212.Packing

/-- **Three-factor extraction.** Suppose every tuple of `Ξ(B_{j,m}, B_{j',m'}, m, m', δ)` admits a
three-block partition with block sums at most `b₁`, `b₂` and `1/2 - b₁ - a₂`. Then every `q`
generated by the support at `(j, j', m, m')` with `q ≥ x^{1/2 - ε₀(1/2 - b₁ - a₂)}` has divisors
`u ∈ [x^{a₂}, x^{b₂}]` and `r ∈ [x^{a₁}, x^{b₁}]` with `u · r ∣ q` — that is, a factorization
`q = u v r`.

The window widths `aᵢ + δ ≤ bᵢ` are needed for each draw, and `b₁ - b₂ ≥ a₁ - a₂` is what makes the
second window reachable after the first draw has been served. -/
@[gap212 "lem_partition2"]
theorem three_factor {p : SupportParams} {x ε₀ a₁ b₁ a₂ b₂ : ℝ} {j j' : Fin p.n} {m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hδ : 0 < p.δ) (hε₀ : 0 < ε₀) (hε₀1 : ε₀ < 1)
    (ha₁ : 0 < a₁) (ha₂ : 0 < a₂)
    (hw₁ : a₁ + p.δ ≤ b₁) (hw₂ : a₂ + p.δ ≤ b₂)
    (hstep : a₁ - a₂ ≤ b₁ - b₂)
    (hB : p.B j m ≤ 1) (hB' : p.B j' m' ≤ 1)
    (hpack : ∀ y ∈ Xi (p.B j m) (p.B j' m') m m' p.δ,
      AdmitsPartition₃ y b₁ b₂ (1 / 2 - b₁ - a₂))
    (hq : q ∈ Qgen p x j j' m m' ε₀)
    (hqbig : x ^ (1 / 2 - ε₀ * (1 / 2 - b₁ - a₂)) ≤ (q : ℝ)) :
    ∃ u r : ℕ, u * r ∣ q ∧
      x ^ a₂ ≤ (u : ℝ) ∧ (u : ℝ) ≤ x ^ b₂ ∧
      x ^ a₁ ≤ (r : ℝ) ∧ (r : ℝ) ≤ x ^ b₁ := by
  classical
  obtain ⟨S, F, y, hq1, hS1, hsm, hF1, hqF, hmem, hlogF, hynn⟩ :=
    xi_of_qgen hx hδ hε₀ hε₀1 hB hB' hq
  obtain ⟨I₁, I₂, hdisj, hI₁, hI₂, hI₃⟩ := hpack _ hmem
  have hb₁0 : 0 < b₁ := by linarith
  have hb₂0 : 0 < b₂ := by linarith
  have hprodF1 : 1 ≤ ∏ i, F i := Finset.one_le_prod' fun i _ ↦ hF1 i
  set R₁ : ℕ := ∏ i ∈ I₁, F i with hR₁_def
  set R₂ : ℕ := ∏ i ∈ I₂, F i with hR₂_def
  have hR₁1 : 1 ≤ R₁ := Finset.one_le_prod' fun i _ ↦ hF1 i
  have hR₂1 : 1 ≤ R₂ := Finset.one_le_prod' fun i _ ↦ hF1 i
  -- Each selected block sits under its own window's top.
  have hsize : ∀ (J : Finset (Fin (m + m'))) (c : ℝ), ∑ i ∈ J, y i ≤ c → 0 ≤ c →
      ((∏ i ∈ J, F i : ℕ) : ℝ) ≤ x ^ c := by
    intro J c hJ hc
    refine prod_le_rpow_of_sum_le hx J F (fun i _ ↦ hF1 i) ?_
    have hEq : ∑ i ∈ J, logb x (F i) = (1 - ε₀) * ∑ i ∈ J, y i := by
      rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
    have hnn : 0 ≤ ∑ i ∈ J, y i := Finset.sum_nonneg fun i _ ↦ hynn i
    rw [hEq]
    nlinarith [mul_nonneg hε₀.le hnn]
  have hR₁b : (R₁ : ℝ) ≤ x ^ b₁ := hsize I₁ b₁ hI₁ hb₁0.le
  have hR₂b : (R₂ : ℝ) ≤ x ^ b₂ := hsize I₂ b₂ hI₂ hb₂0.le
  -- The two selected blocks are disjoint, so their products multiply into `∏ F`.
  have hunion : R₁ * R₂ = ∏ i ∈ I₁ ∪ I₂, F i := (Finset.prod_union hdisj).symm
  have hdvdF : R₁ * R₂ ∣ ∏ i, F i := by
    rw [hunion]
    exact prod_subset_dvd_prod (Finset.subset_univ _) F
  have hdvd : R₁ * R₂ * S ∣ q := by
    rw [hqF]; exact mul_dvd_mul_right hdvdF S
  -- Logarithmic bookkeeping. `C` is the third block's capacity.
  set C : ℝ := 1 / 2 - b₁ - a₂ with hC_def
  have hden' : (0 : ℝ) ≤ 1 - ε₀ := by linarith
  have hlogq : logb x (q : ℝ) = ∑ i, logb x (F i) + logb x (S : ℝ) := by
    rw [hqF, logb_mul_nat hprodF1 hS1, logb_prod_nat univ F fun i _ ↦ hF1 i]
  have hlogqbig : 1 / 2 - ε₀ * C ≤ logb x (q : ℝ) := le_logb_of_rpow_le hx hq1 hqbig
  have hlogI₁ : ∑ i ∈ I₁, logb x (F i) = (1 - ε₀) * ∑ i ∈ I₁, y i := by
    rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
  have hlogI₂ : ∑ i ∈ I₂, logb x (F i) = (1 - ε₀) * ∑ i ∈ I₂, y i := by
    rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
  have hlogRest : ∑ i ∈ univ \ (I₁ ∪ I₂), logb x (F i)
      = (1 - ε₀) * ∑ i ∈ univ \ (I₁ ∪ I₂), y i := by
    rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
  have hI₁nn : 0 ≤ ∑ i ∈ I₁, y i := Finset.sum_nonneg fun i _ ↦ hynn i
  have hRestnn : 0 ≤ ∑ i ∈ univ \ (I₁ ∪ I₂), y i := Finset.sum_nonneg fun i _ ↦ hynn i
  have hsplitU : (∑ i ∈ I₁, logb x (F i)) + ∑ i ∈ I₂, logb x (F i)
      = ∑ i ∈ I₁ ∪ I₂, logb x (F i) := (Finset.sum_union hdisj).symm
  have hcompl : (∑ i ∈ I₁ ∪ I₂, logb x (F i)) + ∑ i ∈ univ \ (I₁ ∪ I₂), logb x (F i)
      = ∑ i, logb x (F i) := Finset.sum_add_sum_compl _ _
  -- The unselected mass costs at most `(1-ε₀)C`, and the first block at most `b₁`.
  have hrest : (1 - ε₀) * (∑ i ∈ univ \ (I₁ ∪ I₂), y i) ≤ (1 - ε₀) * C :=
    mul_le_mul_of_nonneg_left hI₃ hden'
  have hfirst : (1 - ε₀) * (∑ i ∈ I₁, y i) ≤ b₁ := by
    nlinarith [mul_nonneg hε₀.le hI₁nn]
  -- `x^{a₂} ≤ R₂ · S`: drop the first block and the remainder.
  have hbig₂ : x ^ a₂ ≤ ((R₂ * S : ℕ) : ℝ) := by
    have h1 : 1 ≤ R₂ * S := Nat.one_le_iff_ne_zero.mpr (by positivity)
    refine rpow_le_of_le_logb hx h1 ?_
    rw [logb_mul_nat hR₂1 hS1, hR₂_def, logb_prod_nat I₂ F fun i _ ↦ hF1 i]
    linarith [hlogq, hlogqbig, hsplitU, hcompl, hlogI₁, hlogRest, hrest, hfirst]
  -- `x^{a₁ + b₂} ≤ R₁ · R₂ · S`: drop only the remainder. This is where
  -- `b₁ - b₂ ≥ a₁ - a₂` is consumed, as `a₁ + b₂ ≤ b₁ + a₂`.
  have hR₁R₂1 : 1 ≤ R₁ * R₂ := Nat.one_le_iff_ne_zero.mpr (by positivity)
  have hunionprod : logb x ((R₁ * R₂ : ℕ) : ℝ) = ∑ i ∈ I₁ ∪ I₂, logb x (F i) := by
    rw [hunion]; exact logb_prod_nat _ F fun i _ ↦ hF1 i
  have hbig₁ : x ^ (a₁ + b₂) ≤ ((R₁ * R₂ * S : ℕ) : ℝ) := by
    have h1 : 1 ≤ R₁ * R₂ * S := Nat.one_le_iff_ne_zero.mpr (by positivity)
    refine rpow_le_of_le_logb hx h1 ?_
    rw [logb_mul_nat hR₁R₂1 hS1, hunionprod]
    linarith [hlogq, hlogqbig, hcompl, hlogRest, hrest]
  exact exists_two_divisors_window hx hdvd hR₁1 hR₂1 hS1 hR₁b hR₂b
    (fun r hr hd ↦ (hsm r hr hd).le) hbig₂ hbig₁
    (by linarith) (by linarith)

/-- **Three-factor extraction into open windows.** The packing side is unchanged — the *bare*
capacities `b₁`, `b₂` and `1/2 - b₁ - a₂`, with no inward inset — and the modulus threshold `ε₁` is
taken strictly below its bound `ε₀(1/2 - b₁ - a₂)`. The conclusion places both divisors strictly
inside their windows: `x^{a₂} < u < x^{b₂}` and `x^{a₁} < r < x^{b₁}`.

This is `Gap212.Extraction.two_factor_strict` one block wider, and the two strictness mechanisms
are the same two:

* at each top end, from the retreat. A selected block has `log_x Rᵢ = (1 - ε₀) ∑_{Iᵢ} y`, so the
  bare bound `∑_{Iᵢ} y ≤ bᵢ` already gives `log_x Rᵢ ≤ (1 - ε₀) bᵢ < bᵢ`, using `ε₀ > 0` and
  `bᵢ > 0`.
* at the first bottom end, from `ε₁`. Any `ε₁ < ε₀(1/2 - b₁ - a₂)` makes
  `log_x(R₂ S) ≥ a₂ - ε₁ + ε₀(1/2 - b₁ - a₂) > a₂`. The second bottom end comes free, through
  `Gap212.Packing.exists_two_divisors_window_strict`: the first draw's strict top end supplies it.

`ε₁ = ε₀ δ / 2` qualifies whenever `δ ≤ 1/2 - b₁ - a₂`, which is the hypothesis of [2] on the
third block, so one threshold serves every route. Demanding capacities `bᵢ - ϵ` instead would cost
an `ϵ` that Condition C has no slack for at the ends of the Type IIb range. -/
theorem three_factor_strict {p : SupportParams} {x ε₀ ε₁ a₁ b₁ a₂ b₂ : ℝ} {j j' : Fin p.n}
    {m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hδ : 0 < p.δ) (hε₀ : 0 < ε₀) (hε₀1 : ε₀ < 1)
    (ha₁ : 0 < a₁) (ha₂ : 0 < a₂)
    (hw₁ : a₁ + p.δ ≤ b₁) (hw₂ : a₂ + p.δ ≤ b₂)
    (hstep : a₁ - a₂ ≤ b₁ - b₂) (hε₁ : ε₁ < ε₀ * (1 / 2 - b₁ - a₂))
    (hB : p.B j m ≤ 1) (hB' : p.B j' m' ≤ 1)
    (hpack : ∀ y ∈ Xi (p.B j m) (p.B j' m') m m' p.δ,
      AdmitsPartition₃ y b₁ b₂ (1 / 2 - b₁ - a₂))
    (hq : q ∈ Qgen p x j j' m m' ε₀)
    (hqbig : x ^ (1 / 2 - ε₁) ≤ (q : ℝ)) :
    ∃ u r : ℕ, u * r ∣ q ∧
      x ^ a₂ < (u : ℝ) ∧ (u : ℝ) < x ^ b₂ ∧
      x ^ a₁ < (r : ℝ) ∧ (r : ℝ) < x ^ b₁ := by
  classical
  obtain ⟨S, F, y, hq1, hS1, hsm, hF1, hqF, hmem, hlogF, hynn⟩ :=
    xi_of_qgen hx hδ hε₀ hε₀1 hB hB' hq
  obtain ⟨I₁, I₂, hdisj, hI₁, hI₂, hI₃⟩ := hpack _ hmem
  have hb₁0 : 0 < b₁ := by linarith
  have hb₂0 : 0 < b₂ := by linarith
  have hden : (0 : ℝ) < 1 - ε₀ := by linarith
  have hprodF1 : 1 ≤ ∏ i, F i := Finset.one_le_prod' fun i _ ↦ hF1 i
  set R₁ : ℕ := ∏ i ∈ I₁, F i with hR₁_def
  set R₂ : ℕ := ∏ i ∈ I₂, F i with hR₂_def
  have hR₁1 : 1 ≤ R₁ := Finset.one_le_prod' fun i _ ↦ hF1 i
  have hR₂1 : 1 ≤ R₂ := Finset.one_le_prod' fun i _ ↦ hF1 i
  -- Each selected block sits *strictly* under its own window's top: the retreat alone.
  have hsize : ∀ (J : Finset (Fin (m + m'))) (c : ℝ), ∑ i ∈ J, y i ≤ c → 0 < c →
      ((∏ i ∈ J, F i : ℕ) : ℝ) < x ^ c := by
    intro J c hJ hc
    refine prod_lt_rpow_of_sum_lt hx J F (fun i _ ↦ hF1 i) ?_
    have hEq : ∑ i ∈ J, logb x (F i) = (1 - ε₀) * ∑ i ∈ J, y i := by
      rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
    have hnn : 0 ≤ ∑ i ∈ J, y i := Finset.sum_nonneg fun i _ ↦ hynn i
    have hmul : (1 - ε₀) * ∑ i ∈ J, y i ≤ (1 - ε₀) * c :=
      mul_le_mul_of_nonneg_left hJ hden.le
    rw [hEq]
    nlinarith [mul_pos hε₀ hc]
  have hR₁b : (R₁ : ℝ) < x ^ b₁ := hsize I₁ b₁ hI₁ hb₁0
  have hR₂b : (R₂ : ℝ) < x ^ b₂ := hsize I₂ b₂ hI₂ hb₂0
  have hunion : R₁ * R₂ = ∏ i ∈ I₁ ∪ I₂, F i := (Finset.prod_union hdisj).symm
  have hdvdF : R₁ * R₂ ∣ ∏ i, F i := by
    rw [hunion]
    exact prod_subset_dvd_prod (Finset.subset_univ _) F
  have hdvd : R₁ * R₂ * S ∣ q := by
    rw [hqF]; exact mul_dvd_mul_right hdvdF S
  -- Logarithmic bookkeeping, as in the non-strict form.
  set C : ℝ := 1 / 2 - b₁ - a₂ with hC_def
  have hlogq : logb x (q : ℝ) = ∑ i, logb x (F i) + logb x (S : ℝ) := by
    rw [hqF, logb_mul_nat hprodF1 hS1, logb_prod_nat univ F fun i _ ↦ hF1 i]
  have hlogqbig : 1 / 2 - ε₁ ≤ logb x (q : ℝ) := le_logb_of_rpow_le hx hq1 hqbig
  have hlogI₁ : ∑ i ∈ I₁, logb x (F i) = (1 - ε₀) * ∑ i ∈ I₁, y i := by
    rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
  have hlogRest : ∑ i ∈ univ \ (I₁ ∪ I₂), logb x (F i)
      = (1 - ε₀) * ∑ i ∈ univ \ (I₁ ∪ I₂), y i := by
    rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
  have hI₁nn : 0 ≤ ∑ i ∈ I₁, y i := Finset.sum_nonneg fun i _ ↦ hynn i
  have hsplitU : (∑ i ∈ I₁, logb x (F i)) + ∑ i ∈ I₂, logb x (F i)
      = ∑ i ∈ I₁ ∪ I₂, logb x (F i) := (Finset.sum_union hdisj).symm
  have hcompl : (∑ i ∈ I₁ ∪ I₂, logb x (F i)) + ∑ i ∈ univ \ (I₁ ∪ I₂), logb x (F i)
      = ∑ i, logb x (F i) := Finset.sum_add_sum_compl _ _
  have hrest : (1 - ε₀) * (∑ i ∈ univ \ (I₁ ∪ I₂), y i) ≤ (1 - ε₀) * C :=
    mul_le_mul_of_nonneg_left hI₃ hden.le
  have hfirst : (1 - ε₀) * (∑ i ∈ I₁, y i) ≤ b₁ := by
    nlinarith [mul_nonneg hε₀.le hI₁nn]
  -- `x^{a₂} < R₂ · S`: the threshold `ε₁` sits strictly below `ε₀ C`.
  have hbig₂ : x ^ a₂ < ((R₂ * S : ℕ) : ℝ) := by
    have h1 : 1 ≤ R₂ * S := Nat.one_le_iff_ne_zero.mpr (by positivity)
    refine rpow_lt_of_lt_logb hx h1 ?_
    rw [logb_mul_nat hR₂1 hS1, hR₂_def, logb_prod_nat I₂ F fun i _ ↦ hF1 i]
    have hC : ε₁ < ε₀ * C := hε₁
    linarith [hlogq, hlogqbig, hsplitU, hcompl, hlogI₁, hlogRest, hrest, hfirst]
  -- `x^{a₁ + b₂} ≤ R₁ · R₂ · S` stays non-strict; the second window's strictness comes from the
  -- first draw's strict top end inside `exists_two_divisors_window_strict`.
  have hR₁R₂1 : 1 ≤ R₁ * R₂ := Nat.one_le_iff_ne_zero.mpr (by positivity)
  have hunionprod : logb x ((R₁ * R₂ : ℕ) : ℝ) = ∑ i ∈ I₁ ∪ I₂, logb x (F i) := by
    rw [hunion]; exact logb_prod_nat _ F fun i _ ↦ hF1 i
  have hbig₁ : x ^ (a₁ + b₂) ≤ ((R₁ * R₂ * S : ℕ) : ℝ) := by
    have h1 : 1 ≤ R₁ * R₂ * S := Nat.one_le_iff_ne_zero.mpr (by positivity)
    refine rpow_le_of_le_logb hx h1 ?_
    rw [logb_mul_nat hR₁R₂1 hS1, hunionprod]
    have hC : ε₁ < ε₀ * C := hε₁
    linarith [hlogq, hlogqbig, hcompl, hlogRest, hrest]
  exact exists_two_divisors_window_strict hx hdvd hR₁1 hR₂1 hS1 hR₁b hR₂b hsm hbig₂ hbig₁
    (by linarith) (by linarith)

end Gap212.Extraction
