/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import Gap212.Extraction.Setup
public meta import Gap212.Attr

/-!
# Two-factor extraction

The first factor-extraction lemma. Given the two-block packing condition on `Ξ`, every
sufficiently large modulus generated by the support has a divisor in a prescribed window
`[x^a, x^b]`, provided the window is at least as wide as the roughness threshold, `b - a ≥ δ`.

## The argument

`Gap212.Extraction.xi_of_qgen` supplies the reservoir `S = e e'`, the pooled rough factors `F`, and
the pooled rescaled logarithms `y ∈ Ξ`. The packing condition then returns a block `I` with

    ∑_{i ∈ I} yᵢ ≤ b        and        ∑_{i ∉ I} yᵢ ≤ 1/2 - a.

Take `R = ∏_{i ∈ I} Fᵢ`. The first bound gives `R ≤ x^{(1-ε₀)b} ≤ x^b`. For the lower end,

    log_x(R · S) = log_x q - ∑_{i ∉ I} log_x Fᵢ ≥ (1/2 - ε₁) - (1-ε₀)(1/2 - a) ≥ a,

the last step holding exactly when `ε₁ ≤ ε₀(1/2 - a)`. Then
`Gap212.Packing.exists_divisor_window` finishes.

## `ε₁` is not existentially quantified here

[2] says "there exists a constant `ε₁ > 0` (dependent only on `ε₀` and `δ`)" and leaves it at
that. The computation above pins it down: `ε₁ = ε₀(1/2 - a)` works, and that is what the hypothesis
`hqbig` below states. Making it explicit is strictly stronger than the formulation of [2], and it
avoids carrying an unspecified constant through the routing argument — where all three extraction
lemmas are invoked across six routes, and six unnamed constants would have to be reconciled.

## Where the unselected rough factors go

Nowhere — they are part of the modulus but not of the divisor. This is why
`exists_divisor_window` asks only that `R · S ∣ q`, and why its size hypothesis is on `R · S`
rather than on `q`.

## Main results

* `Gap212.Extraction.two_factor`: the lemma.
-/

@[expose] public section

namespace Gap212.Extraction

open Finset Real Gap212.Packing

/-- **Two-factor extraction.** Suppose every tuple of `Ξ(B_{j,m}, B_{j',m'}, m, m', δ)` admits a
two-block partition with block sums at most `b` and `1/2 - a`. Then every `q` generated by the
support at `(j, j', m, m')` with `q ≥ x^{1/2 - ε₀(1/2-a)}` has a divisor in `[x^a, x^b]`, provided
`a + δ ≤ b`. -/
@[gap212 "lem_partition1"]
theorem two_factor {p : SupportParams} {x ε₀ a b : ℝ} {j j' : Fin p.n} {m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hδ : 0 < p.δ) (hε₀ : 0 < ε₀) (hε₀1 : ε₀ < 1)
    (ha : 0 < a) (hab : a + p.δ ≤ b)
    (hB : p.B j m ≤ 1) (hB' : p.B j' m' ≤ 1)
    (hpack : ∀ y ∈ Xi (p.B j m) (p.B j' m') m m' p.δ, AdmitsPartition₂ y b (1 / 2 - a))
    (hq : q ∈ Qgen p x j j' m m' ε₀)
    (hqbig : x ^ (1 / 2 - ε₀ * (1 / 2 - a)) ≤ (q : ℝ)) :
    ∃ r, r ∣ q ∧ x ^ a ≤ (r : ℝ) ∧ (r : ℝ) ≤ x ^ b := by
  classical
  obtain ⟨S, F, y, hq1, hS1, hsm, hF1, hqF, hmem, hlogF, hynn⟩ :=
    xi_of_qgen hx hδ hε₀ hε₀1 hB hB' hq
  obtain ⟨I, hI1, hI2⟩ := hpack _ hmem
  have hb0 : 0 < b := by linarith
  have hprodF1 : 1 ≤ ∏ i, F i := Finset.one_le_prod' fun i _ ↦ hF1 i
  set R : ℕ := ∏ i ∈ I, F i with hR_def
  have hR1 : 1 ≤ R := Finset.one_le_prod' fun i _ ↦ hF1 i
  -- `R ≤ x^b`, from the first block bound.
  have hRb : (R : ℝ) ≤ x ^ b := by
    refine prod_le_rpow_of_sum_le hx I F (fun i _ ↦ hF1 i) ?_
    have hEq : ∑ i ∈ I, logb x (F i) = (1 - ε₀) * ∑ i ∈ I, y i := by
      rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
    have hTnn : 0 ≤ ∑ i ∈ I, y i := Finset.sum_nonneg fun i _ ↦ hynn i
    rw [hEq]
    nlinarith [mul_nonneg hε₀.le hTnn]
  -- `R · S ∣ q`.
  have hdvd : R * S ∣ q := by
    rw [hqF]
    exact mul_dvd_mul_right (prod_subset_dvd_prod (Finset.subset_univ I) F) S
  -- `x^a ≤ R · S`, from the second block bound and the size of `q`.
  have hbig : x ^ a ≤ ((R * S : ℕ) : ℝ) := by
    have hRS1 : 1 ≤ R * S := Nat.one_le_iff_ne_zero.mpr (by positivity)
    refine rpow_le_of_le_logb hx hRS1 ?_
    rw [logb_mul_nat hR1 hS1]
    have hlogq : logb x (q : ℝ) = ∑ i, logb x (F i) + logb x (S : ℝ) := by
      rw [hqF, logb_mul_nat hprodF1 hS1, logb_prod_nat univ F fun i _ ↦ hF1 i]
    have hlogR : logb x (R : ℝ) = ∑ i ∈ I, logb x (F i) :=
      logb_prod_nat I F fun i _ ↦ hF1 i
    have hsplit : (∑ i ∈ I, logb x (F i)) + ∑ i ∈ univ \ I, logb x (F i)
        = ∑ i, logb x (F i) := Finset.sum_add_sum_compl I _
    have hEq2 : ∑ i ∈ univ \ I, logb x (F i) = (1 - ε₀) * ∑ i ∈ univ \ I, y i := by
      rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
    have hUnn : 0 ≤ ∑ i ∈ univ \ I, y i := Finset.sum_nonneg fun i _ ↦ hynn i
    have hlogqbig : 1 / 2 - ε₀ * (1 / 2 - a) ≤ logb x (q : ℝ) :=
      le_logb_of_rpow_le hx hq1 hqbig
    rw [hlogR]
    nlinarith [hI2, hUnn, hEq2, hsplit, hlogq, hlogqbig]
  exact exists_divisor_window hx hdvd hR1 hS1 hRb (fun r hr hd ↦ (hsm r hr hd).le) hbig
    (by linarith)

/-- **Two-factor extraction into an open window.** Same hypotheses as
`Gap212.Extraction.two_factor` on the packing side — the *bare* capacities `b` and `1/2 - a`, with
no inward inset — but with the modulus threshold `ε₁` taken strictly below its bound `ε₀(1/2 - a)`.
The conclusion is a divisor in the **open** window: `x^a < r < x^b`.

This is the form `Gap212.HasDivisorIn` and hence every modulus family asks for, and the two
strictnesses come from the two places they must, neither of them a capacity:

* at the top, from the retreat. The selected rough part has `log_x R = (1 - ε₀) ∑_{I₁} y`, so the
  bare bound `∑_{I₁} y ≤ b` already gives `log_x R ≤ (1 - ε₀) b < b`, using `ε₀ > 0` and `b > 0`.
* at the bottom, from `ε₁`. The threshold is ours to choose, and any `ε₁ < ε₀(1/2 - a)` makes
  `log_x (R · S) ≥ a - ε₁ + ε₀(1/2 - a) > a`. The choice `ε₁ = ε₀δ/2` qualifies whenever
  `δ ≤ 1/2 - a`, which is the hypothesis `1/2 - a ≥ δ` of the lemma in [2].

So demanding an open window costs nothing here, and demanding capacities `b - ϵ`, `1/2 - a - ϵ`
would cost an `ϵ` that Conditions A and E have no slack for. -/
theorem two_factor_strict {p : SupportParams} {x ε₀ ε₁ a b : ℝ} {j j' : Fin p.n} {m m' : ℕ} {q : ℕ}
    (hx : 1 < x) (hδ : 0 < p.δ) (hε₀ : 0 < ε₀) (hε₀1 : ε₀ < 1)
    (ha : 0 < a) (hab : a + p.δ ≤ b) (hε₁ : ε₁ < ε₀ * (1 / 2 - a))
    (hB : p.B j m ≤ 1) (hB' : p.B j' m' ≤ 1)
    (hpack : ∀ y ∈ Xi (p.B j m) (p.B j' m') m m' p.δ, AdmitsPartition₂ y b (1 / 2 - a))
    (hq : q ∈ Qgen p x j j' m m' ε₀)
    (hqbig : x ^ (1 / 2 - ε₁) ≤ (q : ℝ)) :
    ∃ r, r ∣ q ∧ x ^ a < (r : ℝ) ∧ (r : ℝ) < x ^ b := by
  classical
  obtain ⟨S, F, y, hq1, hS1, hsm, hF1, hqF, hmem, hlogF, hynn⟩ :=
    xi_of_qgen hx hδ hε₀ hε₀1 hB hB' hq
  obtain ⟨I, hI1, hI2⟩ := hpack _ hmem
  have hb0 : 0 < b := by linarith
  have hden : (0 : ℝ) < 1 - ε₀ := by linarith
  have hprodF1 : 1 ≤ ∏ i, F i := Finset.one_le_prod' fun i _ ↦ hF1 i
  set R : ℕ := ∏ i ∈ I, F i with hR_def
  have hR1 : 1 ≤ R := Finset.one_le_prod' fun i _ ↦ hF1 i
  -- `R < x^b`: the retreat alone, since `log_x R = (1 - ε₀) ∑_{I} y ≤ (1 - ε₀) b < b`.
  have hRb : (R : ℝ) < x ^ b := by
    refine prod_lt_rpow_of_sum_lt hx I F (fun i _ ↦ hF1 i) ?_
    have hEq : ∑ i ∈ I, logb x (F i) = (1 - ε₀) * ∑ i ∈ I, y i := by
      rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
    have hTnn : 0 ≤ ∑ i ∈ I, y i := Finset.sum_nonneg fun i _ ↦ hynn i
    have hstep : (1 - ε₀) * ∑ i ∈ I, y i ≤ (1 - ε₀) * b :=
      mul_le_mul_of_nonneg_left hI1 hden.le
    rw [hEq]
    nlinarith [mul_pos hε₀ hb0]
  -- `R · S ∣ q`.
  have hdvd : R * S ∣ q := by
    rw [hqF]
    exact mul_dvd_mul_right (prod_subset_dvd_prod (Finset.subset_univ I) F) S
  -- `x^a < R · S`: the threshold `ε₁` sits strictly below `ε₀(1/2 - a)`.
  have hbig : x ^ a < ((R * S : ℕ) : ℝ) := by
    have hRS1 : 1 ≤ R * S := Nat.one_le_iff_ne_zero.mpr (by positivity)
    refine rpow_lt_of_lt_logb hx hRS1 ?_
    rw [logb_mul_nat hR1 hS1]
    have hlogq : logb x (q : ℝ) = ∑ i, logb x (F i) + logb x (S : ℝ) := by
      rw [hqF, logb_mul_nat hprodF1 hS1, logb_prod_nat univ F fun i _ ↦ hF1 i]
    have hlogR : logb x (R : ℝ) = ∑ i ∈ I, logb x (F i) :=
      logb_prod_nat I F fun i _ ↦ hF1 i
    have hsplit : (∑ i ∈ I, logb x (F i)) + ∑ i ∈ univ \ I, logb x (F i)
        = ∑ i, logb x (F i) := Finset.sum_add_sum_compl I _
    have hEq2 : ∑ i ∈ univ \ I, logb x (F i) = (1 - ε₀) * ∑ i ∈ univ \ I, y i := by
      rw [Finset.mul_sum]; exact Finset.sum_congr rfl fun i _ ↦ hlogF i
    have hUstep : (1 - ε₀) * ∑ i ∈ univ \ I, y i ≤ (1 - ε₀) * (1 / 2 - a) :=
      mul_le_mul_of_nonneg_left hI2 hden.le
    have hlogqbig : 1 / 2 - ε₁ ≤ logb x (q : ℝ) := le_logb_of_rpow_le hx hq1 hqbig
    rw [hlogR]
    nlinarith [hEq2, hsplit, hlogq, hlogqbig, hUstep]
  exact exists_divisor_window_strict hx hdvd hR1 hS1 hRb hsm hbig (by linarith)

end Gap212.Extraction
